/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteka;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleCallableStatement;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Karol
 */
public class Administrator_dodajwypozyczenie extends javax.swing.JFrame {
            Connection conn = null;
            CallableStatement stmt = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
     OraclePreparedStatement pst2 = null;
    OracleResultSet rs2 = null;
    public int idksiazki;
public int idwypozyczenia;
public int idkary;
public int idklienta;
    /**
     * Creates new form Administrator_dodajwypozyczenie
     */
    public Administrator_dodajwypozyczenie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Imie", "Nazwisko", "Nr telefonu"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tytuł", "Kategoria", "Autor", "Ilość egzemplarzy"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Dodaj wypożyczenie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Powrót");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3)
                            .addComponent(jTextField10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7)
                            .addComponent(jTextField6)
                            .addComponent(jTextField8)
                            .addComponent(jTextField9)
                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                        .addGap(137, 137, 137))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn = DbAccess.ConnectDb();
        
        try{
           if(conn!=null){
               CallableStatement cs = null;
              cs = conn.prepareCall("call SHOW_KLIENCI_ADMIN(?)");
        cs.registerOutParameter(1, OracleTypes.CURSOR);
        cs.execute();
        ResultSet cursor = ((OracleCallableStatement) cs).getCursor(1);
               
               int i=0;
               while(cursor.next()){
                   jTable1.getModel().setValueAt(cursor.getString(1),i,0);
                   jTable1.getModel().setValueAt(cursor.getString(2),i,1);
                   jTable1.getModel().setValueAt(cursor.getString(3),i,2);
                   jTable1.getModel().setValueAt(cursor.getString(4),i,3);
                                  
                   i++;
               }
           }
       } catch (SQLException ex){
           Logger.getLogger(Administrator_dodajwypozyczenie.class.getName()).log(Level.SEVERE,null,ex);
       }
       try{
           if(conn!=null){
               CallableStatement cs = null;
              cs = conn.prepareCall("call SHOW_BOOKS_ADMIN(?)");
        cs.registerOutParameter(1, OracleTypes.CURSOR);
        cs.execute();
        ResultSet cursor = ((OracleCallableStatement) cs).getCursor(1);
               
               int i=0;
               while(cursor.next()){
                   jTable2.getModel().setValueAt(cursor.getString(1),i,0);
                   jTable2.getModel().setValueAt(cursor.getString(2),i,1);
                   jTable2.getModel().setValueAt(cursor.getString(3),i,2);
                   jTable2.getModel().setValueAt(cursor.getString(4)+" "+cursor.getString(5),i,3);
                   jTable2.getModel().setValueAt(cursor.getString(6),i,4);                 
                   i++;
               }
           }
       } catch (SQLException ex){
           Logger.getLogger(Administrator_dodajwypozyczenie.class.getName()).log(Level.SEVERE,null,ex);
       }
    }//GEN-LAST:event_formWindowOpened

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
       int selectedRowIndex = jTable2.getSelectedRow();
       jTextField11.setText(model.getValueAt(selectedRowIndex,0).toString());
       jTextField6.setText(model.getValueAt(selectedRowIndex,1).toString());
       jTextField7.setText(model.getValueAt(selectedRowIndex,2).toString());
       jTextField8.setText(model.getValueAt(selectedRowIndex,3).toString());
       jTextField9.setText(model.getValueAt(selectedRowIndex,4).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       int selectedRowIndex = jTable1.getSelectedRow();
       jTextField10.setText(model.getValueAt(selectedRowIndex,0).toString());
       jTextField3.setText(model.getValueAt(selectedRowIndex,1).toString());
       jTextField4.setText(model.getValueAt(selectedRowIndex,2).toString());
       jTextField5.setText(model.getValueAt(selectedRowIndex,3).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conn = DbAccess.ConnectDb();
        idklienta = Integer.valueOf(jTextField10.getText());
        idksiazki = Integer.valueOf(jTextField11.getText());
        String dataWyp = jTextField1.getText();
        String dataZwr = jTextField2.getText();
        try{
          if(conn!=null){
               String sql = "select IDWYPOZYCZENIA.nextval from DUAL";        
        pst = (OraclePreparedStatement) conn.prepareStatement(sql);
       rs = (OracleResultSet) pst.executeQuery();
           while(rs.next()){
            int nextID_from_seq;
            nextID_from_seq = rs.getInt(1);
                System.out.println(nextID_from_seq);
                  stmt = conn.prepareCall("call ADD_WYPOZYCZENIE(?,?,?,?,?,?,?,?,?)");
                  
                  idwypozyczenia = nextID_from_seq;
                  
                  stmt.setInt(1,idwypozyczenia);
                  stmt.setInt(2,idksiazki);
                  int idpracownika = 1; //Domyślnie administrator
                  stmt.setInt(3, idpracownika);
                  stmt.setInt(4,idklienta);
                  try {
                   Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(dataWyp);
                  java.sql.Date data = new java.sql.Date(date1.getTime());
                    stmt.setDate(5, data);
                    Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(dataZwr);
                  java.sql.Date data2 = new java.sql.Date(date2.getTime());
                  stmt.setDate(6,data2);
               } catch (ParseException ex) {
                   Logger.getLogger(Administrator_dodajwypozyczenie.class.getName()).log(Level.SEVERE, null, ex);
               }
                  /*
                  Calendar cal = Calendar.getInstance();
                  Date currentDate = new Date();
                  cal.setTime(currentDate);
                  
                  java.sql.Date dataWyp = new java.sql.Date(cal.getTimeInMillis());
                  stmt.setDate(5, dataWyp);
                  cal.add(Calendar.DATE, 14);
                  java.sql.Date dataZwrotu = new java.sql.Date(cal.getTimeInMillis());
                  
                  stmt.setDate(6, dataZwrotu);
                  */
                  int karaID = 5;
                  stmt.setInt(7, karaID);
                  System.out.println("id kary "+idkary);
                  int naleznosc = 0; //Naleznosc na początku wynosi 0
                  stmt.setInt(8, naleznosc);
                   stmt.registerOutParameter(9, java.sql.Types.VARCHAR);
            stmt.executeUpdate();
            String result = stmt.getString(9);
            System.out.println("Dodano wypożyczenie: "+result);
              
          }
          }
           } catch (SQLException ex){
           Logger.getLogger(Administrator_dodajwypozyczenie.class.getName()).log(Level.SEVERE,null,ex);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator_dodajwypozyczenie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator_dodajwypozyczenie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator_dodajwypozyczenie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator_dodajwypozyczenie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator_dodajwypozyczenie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
